name: ci

on:
  workflow_call:
    inputs:
      runs-on:
        default: "ubuntu-latest"
        required: false
        type: string
      image-tag:
        required: true
        type: string
      target-stage:
        required: false
        type: string
      docker-context:
        required: false
        type: string
      dockerfile-path:
        required: false
        type: string
      docker-registry:
        default: "registry.gitlab.com"
        required: false
        type: string

    secrets:
      npm-token:
        required: false
      docker-registry-username:
        required: false
      docker-registry-password:
        required: false

jobs:
  docker:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Use cache only on git hub hosted runner
      - if: ${{ !contains( inputs.runs-on , 'self-hosted' ) }}
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - # Why use copy secret to env? See: https://github.com/actions/runner/issues/520#issuecomment-860043020
        env:
          USERNAME: ${{ secrets.docker-registry-username }}
          PASSWORD: ${{ secrets.docker-registry-password }}
        if: ${{ env.USERNAME && env.PASSWORD }}
        name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: create secret file
        env:
          NPM_REGISTRY: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.npm-token }}
        run: |
          echo "//${NPM_REGISTRY##*://}/:_authToken=${NPM_TOKEN}" > /tmp/.npmrc

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-file }}
          target: ${{ inputs.target-stage }}
          tags: ${{ inputs.image-tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          secret-files: |
            "npmrc=/tmp/.npmrc"

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        if: ${{ !contains( inputs.runs-on , 'self-hosted')}}
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
