name: Build frontend app image

on:
  workflow_call:
    inputs:
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string
      target-stage:
        default: ""
        required: false
        type: string
      image-name:
        required: true 
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      npm-token:
        required: false
jobs:
  build-image:
    name: build image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Build test image
        env:
          NPM_REGISTRY: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.npm-token }}
          TARGET_STAGE: ${{ inputs.target-stage }}
        run: |
          export DOCKER_BUILDKIT=1
          BUILD_OPTION=""
          [[ -n "${NPM_TOKEN}" ]] && echo "//${NPM_REGISTRY##*://}/:_authToken=${NPM_TOKEN}" > /tmp/.npmrc && BUILD_OPTION="$BUILD_OPTION --secret id=npmrc,src=/tmp/.npmrc"
          [[ -n "${TARGET_STAGE}" ]] && BUILD_OPTION="$BUILD_OPTION --target $TARGET_STAGE"
          docker build ${BUILD_OPTION} -t ${{ inputs.image-name }}:{{ inputs.image-tag }} .
