name: Reusable workflow example

on:
  workflow_call:
    inputs:
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string
      message:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: echo "Hello World ${{ inputs.message }}"
